on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_json_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Execute Test-Json on all changed JSON files
        shell: pwsh
        run: |
          foreach ($file in ${{ steps.files.outputs.all }} -split " ") {
            if ($file.EndsWith(".json")) {
              $isValidJson = Get-Content $file -Raw | Test-Json
              if (!$isValidJson) {
                throw "File $file contains invalid json content"
                Exit 1
              }
            }
          }
